#!/usr/bin/env python

__author__ = 'david_allison'

import xml.etree.ElementTree as ET
from watcher.watchpuppy import WatchDogBasedSystem
import time
from watcher.watchedfolder import WatchedFolder
from raven import Client as RavenClient
from watcher.tasks import get_dsn, DSNNotFound
import logging
from watcher.global_settings import CONFIG_FILE

"""
Main Python file that should be called to execute the Watchman system.
Please note that we are loading the XML file with a hardcoded name and path due to tasks.py also needing to access the same file.
"""

folders = {}

#START MAIN

tree = ET.parse(CONFIG_FILE)
root = tree.getroot()

try:
    raven_client = RavenClient(get_dsn(tree), raise_exception=True)
except DSNNotFound:
    logging.error("No Sentry DSN in the settings file, errors will not be logged to Sentry")
    raven_client = None

for record in tree.findall("path"):
    f=WatchedFolder(record=record, raven_client=raven_client)
    folders[f.location] = f
    print f.__unicode__()
    s = WatchDogBasedSystem(location=f.location, stable_time=f.stable_time)
    s.daemon = True
    folders[f.location].kennel = s
    s.start()

while True:
    time.sleep(3600)
